[package]
name = "factrs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[dev-dependencies]
tempfile = "3.10.1"
